/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import javax.swing.JFrame;
import main.Hangman;

/**
 *
 * @author rabey
 */
public class GameOverPage extends javax.swing.JFrame {

    /**
     * Creates new form GameOverPage
     */
    static int score;
    static String username;
    static String moviename;
    static int filepath;
    public GameOverPage(int score,String word,int filepath) {
        this.filepath=filepath;
        this.score=score;
        this.moviename=word;
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        consolationmsg.setText(Hangman.randomConsolationMessage());
        wordtoguessmsg.setText(word.toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usertxt = new javax.swing.JTextField();
        enterbutton = new javax.swing.JButton();
        enternamemsg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        playagainbutton = new javax.swing.JButton();
        consolationmsg = new javax.swing.JLabel();
        wordtoguessmsg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usertxt.setBackground(new java.awt.Color(241, 162, 248));
        usertxt.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        usertxt.setForeground(new java.awt.Color(255, 255, 255));
        usertxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usertxt.setText("Guest");
        usertxt.setToolTipText("Enter Your Name Here");
        usertxt.setActionCommand("null");
        usertxt.setBorder(null);
        usertxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });
        getContentPane().add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 260, 30));

        enterbutton.setBackground(new java.awt.Color(154, 98, 250));
        enterbutton.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 36)); // NOI18N
        enterbutton.setForeground(new java.awt.Color(255, 242, 252));
        enterbutton.setText("Enter");
        enterbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255)));
        enterbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(enterbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 110, 40));

        enternamemsg.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        enternamemsg.setForeground(new java.awt.Color(250, 199, 253));
        enternamemsg.setText("Enter Your Name");
        getContentPane().add(enternamemsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Play Again!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, -1, -1));

        playagainbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\rabey\\OneDrive\\Documents\\hangmangraphics\\replay.png")); // NOI18N
        playagainbutton.setBorder(null);
        playagainbutton.setBorderPainted(false);
        playagainbutton.setContentAreaFilled(false);
        playagainbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playagainbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(playagainbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, 140, 50));

        consolationmsg.setFont(new java.awt.Font("Segoe Script", 1, 48)); // NOI18N
        consolationmsg.setForeground(new java.awt.Color(255, 222, 255));
        consolationmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consolationmsg.setText("Good Try!");
        consolationmsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(consolationmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1285, -1));

        wordtoguessmsg.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        wordtoguessmsg.setForeground(new java.awt.Color(255, 200, 252));
        wordtoguessmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wordtoguessmsg.setText("\"Jab Tak Hain Jaan\"");
        wordtoguessmsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(wordtoguessmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1285, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rabey\\OneDrive\\Documents\\hangmangraphics\\gameover.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    private void enterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterbuttonActionPerformed
        // TODO add your handling code here:
        String name=usertxt.getText();
        username=name;
        Hangman.updateHighScore(score, username);
        HighScoreForm hsp= new HighScoreForm();
        hsp.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_enterbuttonActionPerformed

    private void playagainbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playagainbuttonActionPerformed
        // TODO add your handling code here:
        String name=usertxt.getText();
        username=name;
        Hangman.updateHighScore(score, username);
        HangmanPlayForm hpf= new HangmanPlayForm(0,filepath);
        hpf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_playagainbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOverPage(score,moviename,filepath).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consolationmsg;
    private javax.swing.JButton enterbutton;
    private javax.swing.JLabel enternamemsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton playagainbutton;
    private javax.swing.JTextField usertxt;
    private javax.swing.JLabel wordtoguessmsg;
    // End of variables declaration//GEN-END:variables
}
