/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

/**
 *
 * @author rabey
 */
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.Hangman;
import javax.swing.JFrame;
public class HangmanPlayForm extends javax.swing.JFrame {

    /**
     * Creates new form HangmanPlayForm
     */
    static int score=0;
    String wordtoguess;
    String guessed="";
    int wrongcount=0;
    int rightcount=0;
    int correctcharcount=0;
    static int highestscore=0;
    static String filepath;
    static int filepath_index;
    static String[] filepaths={"C:\\Users\\rabey\\OneDrive\\Documents\\NetBeansProjects\\Hangman\\src\\main\\java\\main\\BollywoodMovieName.txt","C:\\Users\\rabey\\OneDrive\\Documents\\NetBeansProjects\\Hangman\\src\\main\\java\\main\\HollywoodMovieName.txt","C:\\Users\\rabey\\OneDrive\\Documents\\NetBeansProjects\\Hangman\\src\\main\\java\\main\\SATVocabulary.txt"};
    public HangmanPlayForm(int score,int filepath_index) {
        int x=0;
        this.filepath_index=filepath_index;
        if(filepath_index<3){
            this.filepath=filepaths[filepath_index];
            //System.out.println(filepath);
        }else{
            Random random= new Random();
            x=random.nextInt(filepath_index);
            this.filepath=filepaths[x];
            
        }
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        wordtoguess=Hangman.randomNameGenerator(filepath);
        guessword.setText(Hangman.returnGappedString(wordtoguess, guessed));
        scorecard.setText("Your Score: "+score);
        highestscore=Hangman.returnHighestScore();
        if(score>highestscore){
            highscorecard.setText("Highest Score: "+score);
        }else{
            highscorecard.setText("Highest Score: "+highestscore);
        }
        correctcharcount=Hangman.returnCorrectCharCount(wordtoguess);
        if(filepath_index==3){
            String m="Guess From The Grand Mix (";
            if(x==2){
                m=m+"Vocabulary)";
            }else if(x==1){
                m=m+"Hollywood)";
            }else{
                m=m+"Bollywood)";
            }
            guessmessage.setText(m);
            
        }else if(filepath_index==2){
            guessmessage.setText("Guess From The Vocabulary");
        }else if(filepath_index==1){
            guessmessage.setText("Guess The Hollywood MOvie");
        }else{
            guessmessage.setText("Guess The Bollywood MOvie");
        }
        if(score>=5){
        hintbutton.setEnabled(true);
        }else{
        hintbutton.setEnabled(false);
        }
    }
    void hangmanSetter(){
            wrongs.setText(wrongcount+"/7");
            if(wrongcount==0){
            wrong1.setText("");
            wrong2.setText("");
            wrong3.setText("");
            wrong4.setText("");
            wrong5.setText("");
            wrong6.setText("");
            wrong7.setText("");
            }
            if(wrongcount==1){
                wrong1.setText("|");
            }
            if(wrongcount==2){
                wrong2.setText("o");
            }
            if(wrongcount==3){
                wrong3.setText("|");
            }
            if(wrongcount==4){
                wrong4.setText("\\");
            }
            if(wrongcount==5){
                wrong5.setText("/");
            }
            if(wrongcount==6){
                wrong6.setText("\\");
            }
            if(wrongcount==7){
                wrong7.setText("/");
            }
    }
    void pressedGuessKeyAction(String k){
            guessed+=k;
            guessword.setText(Hangman.returnGappedString(wordtoguess, guessed));
            if(Hangman.statusCheck(k, wordtoguess)){
                rightcount++;
            }else{
                wrongcount++;
                hangmanSetter();
            }
        
    }
    void actionStatus(){
         if(wrongcount==7){
            GameOverPage gof= new GameOverPage(score,wordtoguess,filepath_index);
            gof.setVisible(true);
            this.dispose();
        }
        if(rightcount==correctcharcount){
            score+=10;
            CongratulationsForm cf=new CongratulationsForm(score,filepath_index);
            cf.setVisible(true);
            this.dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_s = new javax.swing.JButton();
        button_a = new javax.swing.JButton();
        button_d = new javax.swing.JButton();
        button_f = new javax.swing.JButton();
        button_hyphen = new javax.swing.JButton();
        button_x = new javax.swing.JButton();
        button_c = new javax.swing.JButton();
        button_v = new javax.swing.JButton();
        button_q = new javax.swing.JButton();
        button_w = new javax.swing.JButton();
        button_e = new javax.swing.JButton();
        button_r = new javax.swing.JButton();
        button_g = new javax.swing.JButton();
        button_h = new javax.swing.JButton();
        button_j = new javax.swing.JButton();
        button_k = new javax.swing.JButton();
        button_t = new javax.swing.JButton();
        button_y = new javax.swing.JButton();
        button_u = new javax.swing.JButton();
        button_i = new javax.swing.JButton();
        button_b = new javax.swing.JButton();
        button_n = new javax.swing.JButton();
        button_m = new javax.swing.JButton();
        button_p = new javax.swing.JButton();
        button_l = new javax.swing.JButton();
        button_o = new javax.swing.JButton();
        wrong2 = new javax.swing.JLabel();
        guessword = new javax.swing.JLabel();
        wrongs = new javax.swing.JLabel();
        hangerline = new javax.swing.JLabel();
        wrong5 = new javax.swing.JLabel();
        wrong1 = new javax.swing.JLabel();
        wrong3 = new javax.swing.JLabel();
        wrong7 = new javax.swing.JLabel();
        wrong6 = new javax.swing.JLabel();
        wrong4 = new javax.swing.JLabel();
        guessmessage = new javax.swing.JLabel();
        highscorecard = new javax.swing.JLabel();
        scorecard = new javax.swing.JLabel();
        hintbutton = new javax.swing.JButton();
        replaybutton = new javax.swing.JButton();
        wrongguessmsg = new javax.swing.JLabel();
        button_1 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();
        button_9 = new javax.swing.JButton();
        button_0 = new javax.swing.JButton();
        button_z = new javax.swing.JButton();
        button_colon = new javax.swing.JButton();
        button_exclamation = new javax.swing.JButton();
        button_dot = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        lab2 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        hintmsg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 10, 73));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_s.setBackground(new java.awt.Color(204, 153, 255));
        button_s.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_s.setText("S");
        button_s.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sActionPerformed(evt);
            }
        });
        getContentPane().add(button_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 60, 40));

        button_a.setBackground(new java.awt.Color(204, 153, 255));
        button_a.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_a.setText("A");
        button_a.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_aActionPerformed(evt);
            }
        });
        getContentPane().add(button_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 60, 40));

        button_d.setBackground(new java.awt.Color(204, 153, 255));
        button_d.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_d.setText("D");
        button_d.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dActionPerformed(evt);
            }
        });
        getContentPane().add(button_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 60, 40));

        button_f.setBackground(new java.awt.Color(204, 153, 255));
        button_f.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_f.setText("F");
        button_f.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_fActionPerformed(evt);
            }
        });
        getContentPane().add(button_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 60, 40));

        button_hyphen.setBackground(new java.awt.Color(204, 153, 255));
        button_hyphen.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_hyphen.setText("-");
        button_hyphen.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_hyphen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hyphenActionPerformed(evt);
            }
        });
        getContentPane().add(button_hyphen, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 60, 40));

        button_x.setBackground(new java.awt.Color(204, 153, 255));
        button_x.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_x.setText("X");
        button_x.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_xActionPerformed(evt);
            }
        });
        getContentPane().add(button_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 60, 40));

        button_c.setBackground(new java.awt.Color(204, 153, 255));
        button_c.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_c.setText("C");
        button_c.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cActionPerformed(evt);
            }
        });
        getContentPane().add(button_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 60, 40));

        button_v.setBackground(new java.awt.Color(204, 153, 255));
        button_v.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_v.setText("V");
        button_v.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_vActionPerformed(evt);
            }
        });
        getContentPane().add(button_v, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 60, 40));

        button_q.setBackground(new java.awt.Color(204, 153, 255));
        button_q.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_q.setText("Q");
        button_q.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_qActionPerformed(evt);
            }
        });
        getContentPane().add(button_q, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 60, 40));

        button_w.setBackground(new java.awt.Color(204, 153, 255));
        button_w.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_w.setText("W");
        button_w.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_wActionPerformed(evt);
            }
        });
        getContentPane().add(button_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 60, 40));

        button_e.setBackground(new java.awt.Color(204, 153, 255));
        button_e.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_e.setText("E");
        button_e.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_eActionPerformed(evt);
            }
        });
        getContentPane().add(button_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 60, 40));

        button_r.setBackground(new java.awt.Color(204, 153, 255));
        button_r.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_r.setText("R");
        button_r.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_rActionPerformed(evt);
            }
        });
        getContentPane().add(button_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 60, 40));

        button_g.setBackground(new java.awt.Color(204, 153, 255));
        button_g.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_g.setText("G");
        button_g.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_gActionPerformed(evt);
            }
        });
        getContentPane().add(button_g, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 60, 40));

        button_h.setBackground(new java.awt.Color(204, 153, 255));
        button_h.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_h.setText("H");
        button_h.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hActionPerformed(evt);
            }
        });
        getContentPane().add(button_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 60, 40));

        button_j.setBackground(new java.awt.Color(204, 153, 255));
        button_j.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_j.setText("J");
        button_j.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_jActionPerformed(evt);
            }
        });
        getContentPane().add(button_j, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 60, 40));

        button_k.setBackground(new java.awt.Color(204, 153, 255));
        button_k.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_k.setText("K");
        button_k.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kActionPerformed(evt);
            }
        });
        getContentPane().add(button_k, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 60, 40));

        button_t.setBackground(new java.awt.Color(204, 153, 255));
        button_t.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_t.setText("T");
        button_t.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tActionPerformed(evt);
            }
        });
        getContentPane().add(button_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 60, 40));

        button_y.setBackground(new java.awt.Color(204, 153, 255));
        button_y.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_y.setText("Y");
        button_y.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_yActionPerformed(evt);
            }
        });
        getContentPane().add(button_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 60, 40));

        button_u.setBackground(new java.awt.Color(204, 153, 255));
        button_u.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_u.setText("U");
        button_u.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_uActionPerformed(evt);
            }
        });
        getContentPane().add(button_u, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 60, 40));

        button_i.setBackground(new java.awt.Color(204, 153, 255));
        button_i.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_i.setText("I");
        button_i.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_iActionPerformed(evt);
            }
        });
        getContentPane().add(button_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 60, 40));

        button_b.setBackground(new java.awt.Color(204, 153, 255));
        button_b.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_b.setText("B");
        button_b.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bActionPerformed(evt);
            }
        });
        getContentPane().add(button_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 60, 40));

        button_n.setBackground(new java.awt.Color(204, 153, 255));
        button_n.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_n.setText("N");
        button_n.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nActionPerformed(evt);
            }
        });
        getContentPane().add(button_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 60, 40));

        button_m.setBackground(new java.awt.Color(204, 153, 255));
        button_m.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_m.setText("M");
        button_m.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mActionPerformed(evt);
            }
        });
        getContentPane().add(button_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 60, 40));

        button_p.setBackground(new java.awt.Color(204, 153, 255));
        button_p.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_p.setText("P");
        button_p.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pActionPerformed(evt);
            }
        });
        getContentPane().add(button_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 60, 40));

        button_l.setBackground(new java.awt.Color(204, 153, 255));
        button_l.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_l.setText("L");
        button_l.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_lActionPerformed(evt);
            }
        });
        getContentPane().add(button_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 60, 40));

        button_o.setBackground(new java.awt.Color(204, 153, 255));
        button_o.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_o.setText("O");
        button_o.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_oActionPerformed(evt);
            }
        });
        getContentPane().add(button_o, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 60, 40));

        wrong2.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 120)); // NOI18N
        wrong2.setForeground(new java.awt.Color(102, 102, 255));
        wrong2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(wrong2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, 180, 80));

        guessword.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        guessword.setForeground(new java.awt.Color(204, 204, 255));
        guessword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guessword.setText("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        getContentPane().add(guessword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 700, 130));

        wrongs.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 32)); // NOI18N
        wrongs.setForeground(new java.awt.Color(255, 102, 102));
        wrongs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wrongs.setText("0/7");
        getContentPane().add(wrongs, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 480, 330, 130));

        hangerline.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        hangerline.setForeground(new java.awt.Color(102, 102, 255));
        hangerline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hangerline.setText("___________");
        getContentPane().add(hangerline, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 180, 50));

        wrong5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 70)); // NOI18N
        wrong5.setForeground(new java.awt.Color(102, 102, 255));
        wrong5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(wrong5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 240, 180, 60));

        wrong1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 75)); // NOI18N
        wrong1.setForeground(new java.awt.Color(102, 102, 255));
        wrong1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(wrong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 120, 180, 70));

        wrong3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 100)); // NOI18N
        wrong3.setForeground(new java.awt.Color(102, 102, 255));
        wrong3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(wrong3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 240, 180, 70));

        wrong7.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 70)); // NOI18N
        wrong7.setForeground(new java.awt.Color(102, 102, 255));
        wrong7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(wrong7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 300, 180, 70));

        wrong6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 70)); // NOI18N
        wrong6.setForeground(new java.awt.Color(102, 102, 255));
        wrong6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(wrong6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 300, 180, 70));

        wrong4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 70)); // NOI18N
        wrong4.setForeground(new java.awt.Color(102, 102, 255));
        wrong4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(wrong4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 240, 180, 60));

        guessmessage.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        guessmessage.setForeground(new java.awt.Color(102, 102, 255));
        guessmessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guessmessage.setText("Guess The Bollywood Movie");
        getContentPane().add(guessmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 700, 130));

        highscorecard.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        highscorecard.setForeground(new java.awt.Color(255, 255, 255));
        highscorecard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscorecard.setText("Highest Score: 100");
        getContentPane().add(highscorecard, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -20, 360, 130));

        scorecard.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        scorecard.setForeground(new java.awt.Color(255, 255, 255));
        scorecard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scorecard.setText("Your Score: 100");
        getContentPane().add(scorecard, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 540, 320, 130));

        hintbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\rabey\\OneDrive\\Documents\\hangmangraphics\\hint.png")); // NOI18N
        hintbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(hintbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 80, 30));

        replaybutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\rabey\\OneDrive\\Documents\\hangmangraphics\\replay.png")); // NOI18N
        replaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(replaybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 80, 30));

        wrongguessmsg.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 32)); // NOI18N
        wrongguessmsg.setForeground(new java.awt.Color(102, 102, 255));
        wrongguessmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wrongguessmsg.setText("Wrong Guesses");
        getContentPane().add(wrongguessmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 330, 130));

        button_1.setBackground(new java.awt.Color(204, 153, 255));
        button_1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_1.setText("1");
        button_1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });
        getContentPane().add(button_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 60, 40));

        button_2.setBackground(new java.awt.Color(204, 153, 255));
        button_2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_2.setText("2");
        button_2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_2ActionPerformed(evt);
            }
        });
        getContentPane().add(button_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 60, 40));

        button_3.setBackground(new java.awt.Color(204, 153, 255));
        button_3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_3.setText("3");
        button_3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_3ActionPerformed(evt);
            }
        });
        getContentPane().add(button_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 60, 40));

        button_4.setBackground(new java.awt.Color(204, 153, 255));
        button_4.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_4.setText("4");
        button_4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_4ActionPerformed(evt);
            }
        });
        getContentPane().add(button_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 60, 40));

        button_5.setBackground(new java.awt.Color(204, 153, 255));
        button_5.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_5.setText("5");
        button_5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_5ActionPerformed(evt);
            }
        });
        getContentPane().add(button_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 60, 40));

        button_6.setBackground(new java.awt.Color(204, 153, 255));
        button_6.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_6.setText("6");
        button_6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_6ActionPerformed(evt);
            }
        });
        getContentPane().add(button_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 60, 40));

        button_7.setBackground(new java.awt.Color(204, 153, 255));
        button_7.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_7.setText("7");
        button_7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_7ActionPerformed(evt);
            }
        });
        getContentPane().add(button_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 60, 40));

        button_8.setBackground(new java.awt.Color(204, 153, 255));
        button_8.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_8.setText("8");
        button_8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_8ActionPerformed(evt);
            }
        });
        getContentPane().add(button_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 60, 40));

        button_9.setBackground(new java.awt.Color(204, 153, 255));
        button_9.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_9.setText("9");
        button_9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_9ActionPerformed(evt);
            }
        });
        getContentPane().add(button_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 60, 40));

        button_0.setBackground(new java.awt.Color(204, 153, 255));
        button_0.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_0.setText("0");
        button_0.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_0ActionPerformed(evt);
            }
        });
        getContentPane().add(button_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 60, 40));

        button_z.setBackground(new java.awt.Color(204, 153, 255));
        button_z.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_z.setText("Z");
        button_z.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_zActionPerformed(evt);
            }
        });
        getContentPane().add(button_z, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 60, 40));

        button_colon.setBackground(new java.awt.Color(204, 153, 255));
        button_colon.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_colon.setText(":");
        button_colon.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        button_colon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_colonActionPerformed(evt);
            }
        });
        getContentPane().add(button_colon, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 50, 90));

        button_exclamation.setBackground(new java.awt.Color(204, 153, 255));
        button_exclamation.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_exclamation.setText("!");
        button_exclamation.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        button_exclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exclamationActionPerformed(evt);
            }
        });
        getContentPane().add(button_exclamation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 60, 40));

        button_dot.setBackground(new java.awt.Color(204, 153, 255));
        button_dot.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        button_dot.setText(".");
        button_dot.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        button_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dotActionPerformed(evt);
            }
        });
        getContentPane().add(button_dot, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 50, 90));

        exitbutton.setBackground(new java.awt.Color(33, 10, 72));
        exitbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\rabey\\OneDrive\\Documents\\hangmangraphics\\exit.png")); // NOI18N
        exitbutton.setAlignmentY(0.0F);
        exitbutton.setBorder(null);
        exitbutton.setBorderPainted(false);
        exitbutton.setContentAreaFilled(false);
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(exitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 110, 50));

        lab2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab2.setForeground(new java.awt.Color(255, 255, 255));
        lab2.setText("Hint");
        lab2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 640, 30, -1));

        lab1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab1.setForeground(new java.awt.Color(255, 255, 255));
        lab1.setText("Reset Word");
        getContentPane().add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, -1, -1));

        hintmsg.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        hintmsg.setForeground(new java.awt.Color(204, 255, 204));
        hintmsg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hintmsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hintmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 960, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rabey\\OneDrive\\Documents\\hangmangraphics\\hangmanbg.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_qActionPerformed
        // TODO add your handling code here:
       pressedGuessKeyAction("q");
        if(Hangman.statusCheck("q",wordtoguess)){
            button_q.setBackground(Color.green);
        }else{
            button_q.setBackground(Color.red);
        }
        actionStatus();
        //button_q.setEnabled(false);
    }//GEN-LAST:event_button_qActionPerformed

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
        // TODO add your handling code here:
       pressedGuessKeyAction("1");
        if(Hangman.statusCheck("1",wordtoguess)){
            button_1.setBackground(Color.green);
        }else{
            button_1.setBackground(Color.red);
        }
        actionStatus();
        //button_1.setEnabled(false);
    }//GEN-LAST:event_button_1ActionPerformed

    private void button_colonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_colonActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction(":");
        if(Hangman.statusCheck(":",wordtoguess)){
            button_colon.setBackground(Color.green);
        }else{
            button_colon.setBackground(Color.red);
        }
        actionStatus();
        //button_colon.setEnabled(false);
    }//GEN-LAST:event_button_colonActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        // TODO add your handling code here:
        UserNameForm unf= new UserNameForm(score,wordtoguess);
        unf.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void replaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaybuttonActionPerformed
        // TODO add your handling code here:
        /*
        wordtoguess=Hangman.randomNameGenerator();
        guessword.setText(Hangman.returnGappedString(wordtoguess, guessed));
        correctcharcount=Hangman.returnCorrectCharCount(wordtoguess);
        guessed="";
        wrongcount=0;
        rightcount=0;
        hangmanSetter();
        wrongs.setText(wrongcount+"/7");
        */
        HangmanPlayForm h=new HangmanPlayForm(score,filepath_index);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_replaybuttonActionPerformed

    private void button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_2ActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("2");
        if(Hangman.statusCheck("2",wordtoguess)){
            button_2.setBackground(Color.green);
        }else{
            button_2.setBackground(Color.red);
        }
        actionStatus();
        //button_2.setEnabled(false);
    }//GEN-LAST:event_button_2ActionPerformed

    private void button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_3ActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("3");
        if(Hangman.statusCheck("3",wordtoguess)){
            button_3.setBackground(Color.green);
        }else{
            button_3.setBackground(Color.red);
        }
        actionStatus();
        //button_3.setEnabled(false);
    }//GEN-LAST:event_button_3ActionPerformed

    private void button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_4ActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("4");
        if(Hangman.statusCheck("4",wordtoguess)){
            button_4.setBackground(Color.green);
        }else{
            button_4.setBackground(Color.red);
        }
        actionStatus();
        //button_4.setEnabled(false);
    }//GEN-LAST:event_button_4ActionPerformed

    private void button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_5ActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("5");
        if(Hangman.statusCheck("5",wordtoguess)){
            button_5.setBackground(Color.green);
        }else{
            button_5.setBackground(Color.red);
        }
        actionStatus();
        //button_5.setEnabled(false);
    }//GEN-LAST:event_button_5ActionPerformed

    private void button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_6ActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("6");
        if(Hangman.statusCheck("6",wordtoguess)){
            button_6.setBackground(Color.green);
        }else{
            button_6.setBackground(Color.red);
        }
        actionStatus();
        //button_6.setEnabled(false);
    }//GEN-LAST:event_button_6ActionPerformed

    private void button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_7ActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("7");
        if(Hangman.statusCheck("7",wordtoguess)){
            button_7.setBackground(Color.green);
        }else{
            button_7.setBackground(Color.red);
        }
        actionStatus();
        //button_7.setEnabled(false);
    }//GEN-LAST:event_button_7ActionPerformed

    private void button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_8ActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("8");
        if(Hangman.statusCheck("8",wordtoguess)){
            button_8.setBackground(Color.green);
        }else{
            button_8.setBackground(Color.red);
        }
        actionStatus();
        //button_8.setEnabled(false);
    }//GEN-LAST:event_button_8ActionPerformed

    private void button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_9ActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("9");
        if(Hangman.statusCheck("9",wordtoguess)){
            button_9.setBackground(Color.green);
        }else{
            button_9.setBackground(Color.red);
        }
        actionStatus();
        //button_9.setEnabled(false);
    }//GEN-LAST:event_button_9ActionPerformed

    private void button_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_0ActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("0");
        if(Hangman.statusCheck("0",wordtoguess)){
            button_0.setBackground(Color.green);
        }else{
            button_0.setBackground(Color.red);
        }
        actionStatus();
        //button_0.setEnabled(false);
    }//GEN-LAST:event_button_0ActionPerformed

    private void button_wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_wActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("w");
        if(Hangman.statusCheck("w",wordtoguess)){
            button_w.setBackground(Color.green);
        }else{
            button_w.setBackground(Color.red);
        }
        actionStatus();
        //button_w.setEnabled(false);
    }//GEN-LAST:event_button_wActionPerformed

    private void button_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_eActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("e");
        if(Hangman.statusCheck("e",wordtoguess)){
            button_e.setBackground(Color.green);
        }else{
            button_e.setBackground(Color.red);
        }
        actionStatus();
        //button_e.setEnabled(false);
    }//GEN-LAST:event_button_eActionPerformed

    private void button_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_rActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("r");
        if(Hangman.statusCheck("r",wordtoguess)){
            button_r.setBackground(Color.green);
        }else{
            button_r.setBackground(Color.red);
        }
        actionStatus();
        //button_r.setEnabled(false);
    }//GEN-LAST:event_button_rActionPerformed

    private void button_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("t");
        if(Hangman.statusCheck("t",wordtoguess)){
            button_t.setBackground(Color.green);
        }else{
            button_t.setBackground(Color.red);
        }
        actionStatus();
        //button_t.setEnabled(false);
    }//GEN-LAST:event_button_tActionPerformed

    private void button_yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_yActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("y");
        if(Hangman.statusCheck("y",wordtoguess)){
            button_y.setBackground(Color.green);
        }else{
            button_y.setBackground(Color.red);
        }
        actionStatus();
        //button_y.setEnabled(false);
    }//GEN-LAST:event_button_yActionPerformed

    private void button_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_uActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("u");
        if(Hangman.statusCheck("u",wordtoguess)){
            button_u.setBackground(Color.green);
        }else{
            button_u.setBackground(Color.red);
        }
        actionStatus();
        //button_u.setEnabled(false);
    }//GEN-LAST:event_button_uActionPerformed

    private void button_iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_iActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("i");
        if(Hangman.statusCheck("i",wordtoguess)){
            button_i.setBackground(Color.green);
        }else{
            button_i.setBackground(Color.red);
        }
        actionStatus();
        //button_i.setEnabled(false);
    }//GEN-LAST:event_button_iActionPerformed

    private void button_oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_oActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("o");
        if(Hangman.statusCheck("o",wordtoguess)){
            button_o.setBackground(Color.green);
        }else{
            button_o.setBackground(Color.red);
        }
        actionStatus();
        //button_o.setEnabled(false);
    }//GEN-LAST:event_button_oActionPerformed

    private void button_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("p");
        if(Hangman.statusCheck("p",wordtoguess)){
            button_p.setBackground(Color.green);
        }else{
            button_p.setBackground(Color.red);
        }
        actionStatus();
        //button_p.setEnabled(false);
    }//GEN-LAST:event_button_pActionPerformed

    private void button_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dotActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction(".");
        if(Hangman.statusCheck(".",wordtoguess)){
            button_dot.setBackground(Color.green);
        }else{
            button_dot.setBackground(Color.red);
        }
        actionStatus();
        //button_dot.setEnabled(false);
        
    }//GEN-LAST:event_button_dotActionPerformed

    private void button_exclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exclamationActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("!");
        if(Hangman.statusCheck("!",wordtoguess)){
            button_exclamation.setBackground(Color.green);
        }else{
            button_exclamation.setBackground(Color.red);
        }
        actionStatus();
        //button_exclamation.setEnabled(false);
    }//GEN-LAST:event_button_exclamationActionPerformed

    private void button_hyphenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_hyphenActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("-");
        if(Hangman.statusCheck("-",wordtoguess)){
            button_hyphen.setBackground(Color.green);
        }else{
            button_hyphen.setBackground(Color.red);
        }
        actionStatus();
        //button_hyphen.setEnabled(false);
    }//GEN-LAST:event_button_hyphenActionPerformed

    private void button_zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_zActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("z");
        if(Hangman.statusCheck("z",wordtoguess)){
            button_z.setBackground(Color.green);
        }else{
            button_z.setBackground(Color.red);
        }
        actionStatus();
        //button_z.setEnabled(false);
    }//GEN-LAST:event_button_zActionPerformed

    private void button_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_xActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("x");
        if(Hangman.statusCheck("x",wordtoguess)){
            button_x.setBackground(Color.green);
        }else{
            button_x.setBackground(Color.red);
        }
        actionStatus();
        //button_x.setEnabled(false);
    }//GEN-LAST:event_button_xActionPerformed

    private void button_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("c");
        if(Hangman.statusCheck("c",wordtoguess)){
            button_c.setBackground(Color.green);
        }else{
            button_c.setBackground(Color.red);
        }
        actionStatus();
        //button_c.setEnabled(false);
    }//GEN-LAST:event_button_cActionPerformed

    private void button_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_vActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("v");
        if(Hangman.statusCheck("v",wordtoguess)){
            button_v.setBackground(Color.green);
        }else{
            button_v.setBackground(Color.red);
        }
        actionStatus();
        //button_v.setEnabled(false);
    }//GEN-LAST:event_button_vActionPerformed

    private void button_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("b");
        if(Hangman.statusCheck("b",wordtoguess)){
            button_b.setBackground(Color.green);
        }else{
            button_b.setBackground(Color.red);
        }
        actionStatus();
        //button_b.setEnabled(false);
    }//GEN-LAST:event_button_bActionPerformed

    private void button_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("n");
        if(Hangman.statusCheck("n",wordtoguess)){
            button_n.setBackground(Color.green);
        }else{
            button_n.setBackground(Color.red);
        }
        actionStatus();
        //button_n.setEnabled(false);
    }//GEN-LAST:event_button_nActionPerformed

    private void button_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("m");
        if(Hangman.statusCheck("m",wordtoguess)){
            button_m.setBackground(Color.green);
        }else{
            button_m.setBackground(Color.red);
        }
        actionStatus();
        //button_m.setEnabled(false);
    }//GEN-LAST:event_button_mActionPerformed

    private void button_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_aActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("a");
        if(Hangman.statusCheck("a",wordtoguess)){
            button_a.setBackground(Color.green);
        }else{
            button_a.setBackground(Color.red);
        }
        actionStatus();
        //button_a.setEnabled(false);
    }//GEN-LAST:event_button_aActionPerformed

    private void button_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("s");
        if(Hangman.statusCheck("s",wordtoguess)){
            button_s.setBackground(Color.green);
        }else{
            button_s.setBackground(Color.red);
        }
        actionStatus();
        //button_s.setEnabled(false);
    }//GEN-LAST:event_button_sActionPerformed

    private void button_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("d");
        if(Hangman.statusCheck("d",wordtoguess)){
            button_d.setBackground(Color.green);
        }else{
            button_d.setBackground(Color.red);
        }
        actionStatus();
        //button_d.setEnabled(false);
    }//GEN-LAST:event_button_dActionPerformed

    private void button_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_fActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("f");
        if(Hangman.statusCheck("f",wordtoguess)){
            button_f.setBackground(Color.green);
        }else{
            button_f.setBackground(Color.red);
        }
        actionStatus();
        //button_f.setEnabled(false);
    }//GEN-LAST:event_button_fActionPerformed

    private void button_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_gActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("g");
        if(Hangman.statusCheck("g",wordtoguess)){
            button_g.setBackground(Color.green);
        }else{
            button_g.setBackground(Color.red);
        }
        actionStatus();
        //button_g.setEnabled(false);
    }//GEN-LAST:event_button_gActionPerformed

    private void button_hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_hActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("h");
        if(Hangman.statusCheck("h",wordtoguess)){
            button_h.setBackground(Color.green);
        }else{
            button_h.setBackground(Color.red);
        }
        actionStatus();
        //button_h.setEnabled(false);
    }//GEN-LAST:event_button_hActionPerformed

    private void button_jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_jActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("j");
        if(Hangman.statusCheck("j",wordtoguess)){
            button_j.setBackground(Color.green);
        }else{
            button_j.setBackground(Color.red);
        }
        actionStatus();
        //button_j.setEnabled(false);
    }//GEN-LAST:event_button_jActionPerformed

    private void button_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("k");
        if(Hangman.statusCheck("k",wordtoguess)){
            button_k.setBackground(Color.green);
        }else{
            button_k.setBackground(Color.red);
        }
        actionStatus();
        //button_k.setEnabled(false);
    }//GEN-LAST:event_button_kActionPerformed

    private void button_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_lActionPerformed
        // TODO add your handling code here:
        pressedGuessKeyAction("l");
        if(Hangman.statusCheck("l",wordtoguess)){
            button_l.setBackground(Color.green);
        }else{
            button_l.setBackground(Color.red);
        }
        actionStatus();
        //button_l.setEnabled(false);
    }//GEN-LAST:event_button_lActionPerformed

    private void hintbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintbuttonActionPerformed
        // TODO add your handling code here:
        hintmsg.setText(Hangman.getHint(wordtoguess, filepath));
        hintbutton.setEnabled(false);
        score-=5;
        scorecard.setText("Your Score: "+score);
        if(score>highestscore){
            highscorecard.setText("Highest Score: "+score);
        }else{
            highscorecard.setText("Highest Score: "+highestscore);
        }
    }//GEN-LAST:event_hintbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangmanPlayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangmanPlayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangmanPlayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangmanPlayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HangmanPlayForm(score,filepath_index).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_0;
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_9;
    private javax.swing.JButton button_a;
    private javax.swing.JButton button_b;
    private javax.swing.JButton button_c;
    private javax.swing.JButton button_colon;
    private javax.swing.JButton button_d;
    private javax.swing.JButton button_dot;
    private javax.swing.JButton button_e;
    private javax.swing.JButton button_exclamation;
    private javax.swing.JButton button_f;
    private javax.swing.JButton button_g;
    private javax.swing.JButton button_h;
    private javax.swing.JButton button_hyphen;
    private javax.swing.JButton button_i;
    private javax.swing.JButton button_j;
    private javax.swing.JButton button_k;
    private javax.swing.JButton button_l;
    private javax.swing.JButton button_m;
    private javax.swing.JButton button_n;
    private javax.swing.JButton button_o;
    private javax.swing.JButton button_p;
    private javax.swing.JButton button_q;
    private javax.swing.JButton button_r;
    private javax.swing.JButton button_s;
    private javax.swing.JButton button_t;
    private javax.swing.JButton button_u;
    private javax.swing.JButton button_v;
    private javax.swing.JButton button_w;
    private javax.swing.JButton button_x;
    private javax.swing.JButton button_y;
    private javax.swing.JButton button_z;
    private javax.swing.JButton exitbutton;
    private javax.swing.JLabel guessmessage;
    private javax.swing.JLabel guessword;
    private javax.swing.JLabel hangerline;
    private javax.swing.JLabel highscorecard;
    private javax.swing.JButton hintbutton;
    private javax.swing.JLabel hintmsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JButton replaybutton;
    private javax.swing.JLabel scorecard;
    private javax.swing.JLabel wrong1;
    private javax.swing.JLabel wrong2;
    private javax.swing.JLabel wrong3;
    private javax.swing.JLabel wrong4;
    private javax.swing.JLabel wrong5;
    private javax.swing.JLabel wrong6;
    private javax.swing.JLabel wrong7;
    private javax.swing.JLabel wrongguessmsg;
    private javax.swing.JLabel wrongs;
    // End of variables declaration//GEN-END:variables
}
