/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import main.Hangman;

/**
 *
 * @author rabey
 */
public class HighScoreForm extends javax.swing.JFrame {

    /**
     * Creates new form HighScoreForm
     */
    public HighScoreForm() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        try {
                ArrayList<String> highscores= Hangman.ReadFromFile("C:\\Users\\rabey\\OneDrive\\Documents\\NetBeansProjects\\Hangman\\src\\main\\java\\main\\HangmanHighScore.txt");
                if(highscores.size()<20){
                   while(highscores.size()<=20){
                       highscores.add("Not Set");
                       highscores.add("N/A");
                   }
                }
                ts1.setText("1. "+highscores.get(0));
                ts2.setText("2. "+highscores.get(2));
                ts3.setText("3. "+highscores.get(4));
                ts4.setText("4. "+highscores.get(6));
                ts5.setText("5. "+highscores.get(8));
                ts6.setText("6. "+highscores.get(10));
                ts7.setText("7. "+highscores.get(12));
                ts8.setText("8. "+highscores.get(14));
                ts9.setText("9. "+highscores.get(16));
                ts10.setText("10. "+highscores.get(18));
                sc1.setText(highscores.get(1));
                sc2.setText(highscores.get(3));
                sc3.setText(highscores.get(5));
                sc4.setText(highscores.get(7));
                sc5.setText(highscores.get(9));
                sc6.setText(highscores.get(11));
                sc7.setText(highscores.get(13));
                sc8.setText(highscores.get(15));
                sc9.setText(highscores.get(17));
                sc10.setText(highscores.get(19));
            } catch (Exception ex) {
                System.out.println(ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ts1 = new javax.swing.JLabel();
        sc1 = new javax.swing.JLabel();
        ts2 = new javax.swing.JLabel();
        sc2 = new javax.swing.JLabel();
        ts3 = new javax.swing.JLabel();
        sc3 = new javax.swing.JLabel();
        ts4 = new javax.swing.JLabel();
        sc4 = new javax.swing.JLabel();
        ts5 = new javax.swing.JLabel();
        sc5 = new javax.swing.JLabel();
        ts10 = new javax.swing.JLabel();
        sc10 = new javax.swing.JLabel();
        ts9 = new javax.swing.JLabel();
        sc9 = new javax.swing.JLabel();
        ts8 = new javax.swing.JLabel();
        sc8 = new javax.swing.JLabel();
        ts7 = new javax.swing.JLabel();
        sc7 = new javax.swing.JLabel();
        ts6 = new javax.swing.JLabel();
        sc6 = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ts1.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        ts1.setForeground(new java.awt.Color(255, 204, 255));
        ts1.setText("Topscorer-1");
        getContentPane().add(ts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        sc1.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        sc1.setForeground(new java.awt.Color(255, 204, 255));
        sc1.setText("Score");
        getContentPane().add(sc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        ts2.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        ts2.setForeground(new java.awt.Color(255, 204, 255));
        ts2.setText("Topscorer-1");
        getContentPane().add(ts2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        sc2.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        sc2.setForeground(new java.awt.Color(255, 204, 255));
        sc2.setText("Score");
        getContentPane().add(sc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        ts3.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        ts3.setForeground(new java.awt.Color(255, 204, 255));
        ts3.setText("Topscorer-1");
        getContentPane().add(ts3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        sc3.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        sc3.setForeground(new java.awt.Color(255, 204, 255));
        sc3.setText("Score");
        getContentPane().add(sc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        ts4.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        ts4.setForeground(new java.awt.Color(255, 204, 255));
        ts4.setText("Topscorer-1");
        getContentPane().add(ts4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        sc4.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        sc4.setForeground(new java.awt.Color(255, 204, 255));
        sc4.setText("Score");
        getContentPane().add(sc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        ts5.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        ts5.setForeground(new java.awt.Color(255, 204, 255));
        ts5.setText("Topscorer-1");
        getContentPane().add(ts5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));

        sc5.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        sc5.setForeground(new java.awt.Color(255, 204, 255));
        sc5.setText("Score");
        getContentPane().add(sc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, -1, -1));

        ts10.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        ts10.setForeground(new java.awt.Color(255, 204, 255));
        ts10.setText("Topscorer-1");
        getContentPane().add(ts10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, -1, -1));

        sc10.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        sc10.setForeground(new java.awt.Color(255, 204, 255));
        sc10.setText("Score");
        getContentPane().add(sc10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 510, -1, -1));

        ts9.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        ts9.setForeground(new java.awt.Color(255, 204, 255));
        ts9.setText("Topscorer-1");
        getContentPane().add(ts9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, -1, -1));

        sc9.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        sc9.setForeground(new java.awt.Color(255, 204, 255));
        sc9.setText("Score");
        getContentPane().add(sc9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 450, -1, -1));

        ts8.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        ts8.setForeground(new java.awt.Color(255, 204, 255));
        ts8.setText("Topscorer-1");
        getContentPane().add(ts8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, -1, -1));

        sc8.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        sc8.setForeground(new java.awt.Color(255, 204, 255));
        sc8.setText("Score");
        getContentPane().add(sc8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, -1, -1));

        ts7.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        ts7.setForeground(new java.awt.Color(255, 204, 255));
        ts7.setText("Topscorer-1");
        getContentPane().add(ts7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, -1, -1));

        sc7.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        sc7.setForeground(new java.awt.Color(255, 204, 255));
        sc7.setText("Score");
        getContentPane().add(sc7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 320, -1, -1));

        ts6.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        ts6.setForeground(new java.awt.Color(255, 204, 255));
        ts6.setText("Topscorer-1");
        getContentPane().add(ts6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, -1, -1));

        sc6.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        sc6.setForeground(new java.awt.Color(255, 204, 255));
        sc6.setText("Score");
        getContentPane().add(sc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 250, -1, -1));

        backbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\rabey\\OneDrive\\Documents\\hangmangraphics\\backbutton.png")); // NOI18N
        backbutton.setBorder(null);
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 300, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rabey\\OneDrive\\Documents\\hangmangraphics\\highscores.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        HangmanHomePage hp=new HangmanHomePage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HighScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HighScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HighScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HighScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HighScoreForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel sc1;
    private javax.swing.JLabel sc10;
    private javax.swing.JLabel sc2;
    private javax.swing.JLabel sc3;
    private javax.swing.JLabel sc4;
    private javax.swing.JLabel sc5;
    private javax.swing.JLabel sc6;
    private javax.swing.JLabel sc7;
    private javax.swing.JLabel sc8;
    private javax.swing.JLabel sc9;
    private javax.swing.JLabel ts1;
    private javax.swing.JLabel ts10;
    private javax.swing.JLabel ts2;
    private javax.swing.JLabel ts3;
    private javax.swing.JLabel ts4;
    private javax.swing.JLabel ts5;
    private javax.swing.JLabel ts6;
    private javax.swing.JLabel ts7;
    private javax.swing.JLabel ts8;
    private javax.swing.JLabel ts9;
    // End of variables declaration//GEN-END:variables
}
