/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import static frame.GameOverPage.score;
import static frame.GameOverPage.username;
import javax.swing.JFrame;
import main.Hangman;

/**
 *
 * @author rabey
 */
public class UserNameForm extends javax.swing.JFrame {

    /**
     * Creates new form UserNameForm
     */
    static int score;
    static String name;
    static String moviename;
    public UserNameForm(int score, String word) {
        this.score=score;
        this.moviename=word;
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        consolationmsg.setText("Thank you for playing!");
        wordtoguessmsg.setText(word.toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usertxt = new javax.swing.JTextField();
        enterbutton = new javax.swing.JButton();
        consolationmsg = new javax.swing.JLabel();
        wordtoguessmsg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 10, 73));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usertxt.setBackground(new java.awt.Color(241, 162, 248));
        usertxt.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        usertxt.setForeground(new java.awt.Color(255, 255, 255));
        usertxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usertxt.setText("Guest");
        usertxt.setToolTipText("Enter Your Name Here");
        usertxt.setBorder(null);
        usertxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });
        getContentPane().add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 260, 30));

        enterbutton.setBackground(new java.awt.Color(33, 10, 73));
        enterbutton.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 36)); // NOI18N
        enterbutton.setForeground(new java.awt.Color(255, 242, 252));
        enterbutton.setText("Enter");
        enterbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255)));
        enterbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(enterbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 110, 40));

        consolationmsg.setFont(new java.awt.Font("Segoe Script", 1, 48)); // NOI18N
        consolationmsg.setForeground(new java.awt.Color(255, 222, 255));
        consolationmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consolationmsg.setText("Good Try!");
        consolationmsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(consolationmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1285, -1));

        wordtoguessmsg.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        wordtoguessmsg.setForeground(new java.awt.Color(255, 200, 252));
        wordtoguessmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wordtoguessmsg.setText("\"Jab Tak Hain Jaan\"");
        wordtoguessmsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(wordtoguessmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1285, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\rabey\\OneDrive\\Documents\\hangmangraphics\\usernameform.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rabey\\OneDrive\\Documents\\hangmangraphics\\hangmanbg.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 200, 252));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("\"Jab Tak Hain Jaan\"");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 870, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 200, 252));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("\"Jab Tak Hain Jaan\"");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 870, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    private void enterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterbuttonActionPerformed
        // TODO add your handling code here:
        username= usertxt.getText();
        Hangman.updateHighScore(score, username);
        HighScoreForm hsp= new HighScoreForm();
        hsp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_enterbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserNameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserNameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserNameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserNameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserNameForm(score,moviename).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consolationmsg;
    private javax.swing.JButton enterbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField usertxt;
    private javax.swing.JLabel wordtoguessmsg;
    // End of variables declaration//GEN-END:variables
}
